# Site settings
title: Gemba Blog
email: support@gemba.io
description: > # this means to ignore newlines until "baseurl:"
  On this blog, I share tips on how to use Gemba, and lessons learned while creating it.
#  (Gemba is the Mac app that lets designers deliver assets into Git repositories with a simple drag and drop.)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.gemba.io" # the base hostname & protocol for your site
twitter_username: GembaApp

# Build settings
markdown: kramdown

# http://www.lostdecadegames.com/blog-author-attribution-using-jekyll/
authors:
  yang:
    display_name: Yang Meyer
    gravatar: 405958e4aa35fd9d028f9ceb95448614
    email: yang@gemba.io
    web: http://blog.yangmeyer.de
    twitter: yangmeyer
    short_bio: "Indie &amp; freelance Mac/iOS development &amp; UX design, ultimate frisbee, beerbrewing."